export const itemIconMap: Record<string, string> = {
    "Venda Curativa": "https://arubiku.github.io/R-D-SMP/icons/items/healing_bandage.png",
    "Piedra de Afilar": "https://arubiku.github.io/R-D-SMP/icons/items/whetstone.png",
    "Pan Mohoso": "https://arubiku.github.io/R-D-SMP/icons/items/mossy_bread.png",
    "Antorcha Eterna": "https://arubiku.github.io/R-D-SMP/icons/items/eternity_torch.png",
    "Palo Afilado": "https://arubiku.github.io/R-D-SMP/icons/items/sharp_stick.png",
    "Botas de Cuero Reforzadas": "https://arubiku.github.io/R-D-SMP/icons/items/reinforced_leather_boots.png",
    "Sopa Misteriosa": "https://arubiku.github.io/R-D-SMP/icons/items/mistery_soup.png",
    "Botas de Hermes": "https://arubiku.github.io/R-D-SMP/icons/items/hermes_boots.png",
    "Poción de Olvido": "https://arubiku.github.io/R-D-SMP/icons/items/potion_of_forgetfulness.png",
    "Arco de Hueso": "https://arubiku.github.io/R-D-SMP/icons/items/bone_bow.png",
    "Escudo de Espinas": "https://arubiku.github.io/R-D-SMP/icons/items/thorns_shield.png",
    "Pico de Vidrio": "https://arubiku.github.io/R-D-SMP/icons/items/glass_pickaxe.png",
    "Imán de XP": "https://arubiku.github.io/R-D-SMP/icons/items/experience_magnet.png",
    "Mochila Pequeña": "https://arubiku.github.io/R-D-SMP/icons/items/small_bag.png",
    "Gancho de Agarre": "https://arubiku.github.io/R-D-SMP/icons/items/climb_hook.png",
    "Pico de la Codicia": "https://arubiku.github.io/R-D-SMP/icons/items/greed_pickaxe.png",
    "Manzana de la Discordia": "https://arubiku.github.io/R-D-SMP/icons/items/discordia_apple.png",
    "Tridente de Poseidón": "https://arubiku.github.io/R-D-SMP/icons/items/poseidon_trident.png",
    "Alas Blindadas": "https://arubiku.github.io/R-D-SMP/icons/items/strong_elytras.png",
    "Capa de Invisibilidad": "https://arubiku.github.io/R-D-SMP/icons/items/invisibility_cape.png",
    "Martillo de Guerra": "https://arubiku.github.io/R-D-SMP/icons/items/war_hammer.png",
    "Tótem de Regeneración": "https://arubiku.github.io/R-D-SMP/icons/items/regeneration_totem.png",
    "Tótem del Azar": "https://arubiku.github.io/R-D-SMP/icons/items/random_totem.png",
    "Orbe de Resurrección": "https://arubiku.github.io/R-D-SMP/icons/items/resurection_orb.png",
    "Espada Vampírica": "https://arubiku.github.io/R-D-SMP/icons/items/vampire_sword.png",
    "Pico Destructor de Mundos": "https://arubiku.github.io/R-D-SMP/icons/items/world_destroyer_pickaxe.png",
    "Casco de la Visión Verdadera": "https://arubiku.github.io/R-D-SMP/icons/items/truth_vision_helmet.png",
    "Manzana de Vida": "https://arubiku.github.io/R-D-SMP/icons/items/notch_hearth.png",
    "Corazón de Notch": "https://arubiku.github.io/R-D-SMP/icons/items/notch_hearth.png",
    "Contrato de Alma": "https://arubiku.github.io/R-D-SMP/icons/items/soul_contract.png",
    "Llamada del Vacío": "https://arubiku.github.io/R-D-SMP/icons/items/void_call.png",
    "Huevo de Dragón Real": "https://arubiku.github.io/R-D-SMP/icons/items/real_dragon_egg.png",
    "La Mano de Dios": "https://arubiku.github.io/R-D-SMP/icons/items/god_hand.png"
};
