export const itemIconMap: Record<string, string> = {
    "Venda Curativa": "/icons/items/healing_bandage.png",
    "Piedra de Afilar": "/icons/items/whetstone.png",
    "Pan Mohoso": "/icons/items/mossy_bread.png",
    "Antorcha Eterna": "/icons/items/eternity_torch.png",
    "Palo Afilado": "/icons/items/sharp_stick.png",
    "Botas de Cuero Reforzadas": "/icons/items/reinforced_leather_boots.png",
    "Sopa Misteriosa": "/icons/items/mistery_soup.png",
    "Botas de Hermes": "/icons/items/hermes_boots.png",
    "Poción de Olvido": "/icons/items/potion_of_forgetfulness.png",
    "Arco de Hueso": "/icons/items/bone_bow.png",
    "Escudo de Espinas": "/icons/items/thorns_shield.png",
    "Pico de Vidrio": "/icons/items/glass_pickaxe.png",
    "Imán de XP": "/icons/items/experience_magnet.png",
    "Mochila Pequeña": "/icons/items/small_bag.png",
    "Gancho de Agarre": "/icons/items/climb_hook.png",
    "Pico de la Codicia": "/icons/items/greed_pickaxe.png",
    "Manzana de la Discordia": "/icons/items/discordia_apple.png",
    "Tridente de Poseidón": "/icons/items/poseidon_trident.png",
    "Capa de Invisibilidad": "/icons/items/invisibility_cape.png",
    "Martillo de Guerra": "/icons/items/war_hammer.png",
    "Tótem de Regeneración": "/icons/items/regeneration_totem.png",
    "Tótem del Azar": "/icons/items/random_totem.png",
    "Orbe de Resurrección": "/icons/items/resurection_orb.png",
    "Espada Vampírica": "/icons/items/vampire_sword.png",
    "Pico Destructor de Mundos": "/icons/items/world_destroyer_pickaxe.png",
    "Casco de la Visión Verdadera": "/icons/items/truth_vision_helmet.png",
    "Corazón de Notch": "/icons/items/notch_hearth.png",
    "Contrato de Alma": "/icons/items/soul_contract.png",
    "Llamada del Vacío": "/icons/items/void_call.png",
    "Huevo de Dragón Real": "/icons/items/real_dragon_egg.png",
    "La Mano de Dios": "/icons/items/god_hand.png"
};
